kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-ext
provisioner: ceph.com/rbd
parameters:
  monitors: 192.168.0.10:6789,192.168.0.11:6789
  pool: kube
  adminId: admin
  adminSecretNamespace: kube-system
  adminSecretName: ceph-secret
  userId: kube
  userSecretName: ceph-user-secret
  imageFormat: "2"
  imageFeatures: layering
